name: Continuous Integration
on: [push, pull_request]

jobs:
  compile-windows:
    name: Compile (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc

      - name: Compile
        run: g++ -fdiagnostics-color=always -g $(find ./src -type f -iregex ".*\\.cpp")

  compile-ubuntu:
    name: Compile (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup compiler
        run: sudo apt install -y build-essential

      - name: Compile
        run: g++ -fdiagnostics-color=always -g $(find ./src -type f -iregex ".*\\.cpp")